[build]
  base    = "client"
  command = "npm run build"
  publish = "dist"   # correct since base=client

[[redirects]]
  from = "/api/*"
  to   = "https://homecyclehome-api-docker.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

