[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

# Proxy API calls → Render backend
[[redirects]]
  from = "/api/*"
  to = "https://home-cycle-app.onrender.com/api/:splat"
  status = 200
  force = true

# React Router fallback (prevents 404 on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
