# render.yaml

services:
  # 1) Private Mongo (Docker image + persistent disk)
  - type: pserv                # <— private service
    runtime: image             # pull a prebuilt image
    name: mongo
    image:
      url: docker.io/library/mongo:7
    plan: starter              # free is NOT allowed for private services
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 5
    envVars:
      - key: MONGO_INITDB_ROOT_USERNAME
        value: root
      - key: MONGO_INITDB_ROOT_PASSWORD
        sync: false            # set in Render dashboard at creation time

  # 2) API (build from backend Dockerfile)
  - type: web
    runtime: docker
    name: homecyclehome-api
    branch: feat/render-docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /health
    autoDeployTrigger: commit
    plan: starter            
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
